# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\development\Ui\Asset_Manager\Asset_Manager_tmp_2.ui'
#
# Created: Tue May 03 00:46:45 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Asset_Manager_MainWindow(object):
    def setupUi(self, Asset_Manager_MainWindow):
        Asset_Manager_MainWindow.setObjectName("Asset_Manager_MainWindow")
        Asset_Manager_MainWindow.setWindowModality(QtCore.Qt.NonModal)
        Asset_Manager_MainWindow.resize(280, 490)
        Asset_Manager_MainWindow.setMinimumSize(QtCore.QSize(280, 0))
        Asset_Manager_MainWindow.setMaximumSize(QtCore.QSize(360, 1000))
        Asset_Manager_MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Asset_Manager_MainWindow.setAcceptDrops(False)
        Asset_Manager_MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        Asset_Manager_MainWindow.setDocumentMode(False)
        Asset_Manager_MainWindow.setDockNestingEnabled(True)
        Asset_Manager_MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        Asset_Manager_MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(Asset_Manager_MainWindow)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setAcceptDrops(False)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(260, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(342, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.project_label = QtGui.QLabel(self.groupBox)
        self.project_label.setMinimumSize(QtCore.QSize(115, 25))
        self.project_label.setMaximumSize(QtCore.QSize(155, 16777215))
        self.project_label.setObjectName("project_label")
        self.gridLayout_2.addWidget(self.project_label, 0, 0, 1, 2)
        self.project_comboBox = QtGui.QComboBox(self.groupBox)
        self.project_comboBox.setMinimumSize(QtCore.QSize(115, 25))
        self.project_comboBox.setMaximumSize(QtCore.QSize(155, 16777215))
        self.project_comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.project_comboBox.setFrame(True)
        self.project_comboBox.setObjectName("project_comboBox")
        self.gridLayout_2.addWidget(self.project_comboBox, 0, 2, 1, 2)
        self.asset_anim_label = QtGui.QLabel(self.groupBox)
        self.asset_anim_label.setMinimumSize(QtCore.QSize(115, 25))
        self.asset_anim_label.setMaximumSize(QtCore.QSize(155, 16777215))
        self.asset_anim_label.setObjectName("asset_anim_label")
        self.gridLayout_2.addWidget(self.asset_anim_label, 1, 0, 1, 2)
        self.asset_anim_comboBox = QtGui.QComboBox(self.groupBox)
        self.asset_anim_comboBox.setMinimumSize(QtCore.QSize(115, 25))
        self.asset_anim_comboBox.setMaximumSize(QtCore.QSize(155, 16777215))
        self.asset_anim_comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.asset_anim_comboBox.setFrame(True)
        self.asset_anim_comboBox.setObjectName("asset_anim_comboBox")
        self.gridLayout_2.addWidget(self.asset_anim_comboBox, 1, 2, 1, 2)
        self.asset_type_episode_label = QtGui.QLabel(self.groupBox)
        self.asset_type_episode_label.setMinimumSize(QtCore.QSize(115, 25))
        self.asset_type_episode_label.setMaximumSize(QtCore.QSize(155, 16777215))
        self.asset_type_episode_label.setObjectName("asset_type_episode_label")
        self.gridLayout_2.addWidget(self.asset_type_episode_label, 2, 0, 1, 2)
        self.asset_type_episode_comboBox = QtGui.QComboBox(self.groupBox)
        self.asset_type_episode_comboBox.setMinimumSize(QtCore.QSize(115, 25))
        self.asset_type_episode_comboBox.setMaximumSize(QtCore.QSize(155, 16777215))
        self.asset_type_episode_comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.asset_type_episode_comboBox.setFrame(True)
        self.asset_type_episode_comboBox.setObjectName("asset_type_episode_comboBox")
        self.gridLayout_2.addWidget(self.asset_type_episode_comboBox, 2, 2, 1, 2)
        self.asset_shot_label = QtGui.QLabel(self.groupBox)
        self.asset_shot_label.setMinimumSize(QtCore.QSize(115, 25))
        self.asset_shot_label.setMaximumSize(QtCore.QSize(155, 16777215))
        self.asset_shot_label.setObjectName("asset_shot_label")
        self.gridLayout_2.addWidget(self.asset_shot_label, 3, 0, 1, 2)
        self.asset_shot_comboBox = QtGui.QComboBox(self.groupBox)
        self.asset_shot_comboBox.setMinimumSize(QtCore.QSize(115, 25))
        self.asset_shot_comboBox.setMaximumSize(QtCore.QSize(155, 16777215))
        self.asset_shot_comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.asset_shot_comboBox.setFrame(True)
        self.asset_shot_comboBox.setObjectName("asset_shot_comboBox")
        self.gridLayout_2.addWidget(self.asset_shot_comboBox, 3, 2, 1, 2)
        self.task_label = QtGui.QLabel(self.groupBox)
        self.task_label.setMinimumSize(QtCore.QSize(115, 25))
        self.task_label.setMaximumSize(QtCore.QSize(155, 16777215))
        self.task_label.setObjectName("task_label")
        self.gridLayout_2.addWidget(self.task_label, 4, 0, 1, 2)
        self.task_comboBox = QtGui.QComboBox(self.groupBox)
        self.task_comboBox.setMinimumSize(QtCore.QSize(115, 25))
        self.task_comboBox.setMaximumSize(QtCore.QSize(155, 16777215))
        self.task_comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.task_comboBox.setFrame(True)
        self.task_comboBox.setObjectName("task_comboBox")
        self.gridLayout_2.addWidget(self.task_comboBox, 4, 2, 1, 2)
        self.open_pushButton = QtGui.QPushButton(self.groupBox)
        self.open_pushButton.setMinimumSize(QtCore.QSize(115, 25))
        self.open_pushButton.setMaximumSize(QtCore.QSize(155, 16777215))
        self.open_pushButton.setObjectName("open_pushButton")
        self.gridLayout_2.addWidget(self.open_pushButton, 5, 0, 1, 2)
        self.open_publish_pushButton = QtGui.QPushButton(self.groupBox)
        self.open_publish_pushButton.setMinimumSize(QtCore.QSize(115, 25))
        self.open_publish_pushButton.setMaximumSize(QtCore.QSize(155, 16777215))
        self.open_publish_pushButton.setObjectName("open_publish_pushButton")
        self.gridLayout_2.addWidget(self.open_publish_pushButton, 5, 2, 1, 2)
        self.files_listWidget = QtGui.QListWidget(self.groupBox)
        self.files_listWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.files_listWidget.setObjectName("files_listWidget")
        self.gridLayout_2.addWidget(self.files_listWidget, 6, 0, 1, 4)
        self.save_pushButton = QtGui.QPushButton(self.groupBox)
        self.save_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.save_pushButton.setObjectName("save_pushButton")
        self.gridLayout_2.addWidget(self.save_pushButton, 7, 0, 1, 1)
        self.wip_pushButton = QtGui.QPushButton(self.groupBox)
        self.wip_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.wip_pushButton.setObjectName("wip_pushButton")
        self.gridLayout_2.addWidget(self.wip_pushButton, 7, 1, 1, 2)
        self.publish_pushButton = QtGui.QPushButton(self.groupBox)
        self.publish_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.publish_pushButton.setObjectName("publish_pushButton")
        self.gridLayout_2.addWidget(self.publish_pushButton, 7, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        Asset_Manager_MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Asset_Manager_MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        Asset_Manager_MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(Asset_Manager_MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 280, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFiles = QtGui.QMenu(self.menuBar)
        self.menuFiles.setObjectName("menuFiles")
        Asset_Manager_MainWindow.setMenuBar(self.menuBar)
        self.actionNew_project = QtGui.QAction(Asset_Manager_MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionNew_Asset = QtGui.QAction(Asset_Manager_MainWindow)
        self.actionNew_Asset.setObjectName("actionNew_Asset")
        self.actionNew_Task = QtGui.QAction(Asset_Manager_MainWindow)
        self.actionNew_Task.setObjectName("actionNew_Task")
        self.menuFiles.addAction(self.actionNew_project)
        self.menuFiles.addSeparator()
        self.menuFiles.addAction(self.actionNew_Asset)
        self.menuFiles.addAction(self.actionNew_Task)
        self.menuBar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(Asset_Manager_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Asset_Manager_MainWindow)

    def retranslateUi(self, Asset_Manager_MainWindow):
        Asset_Manager_MainWindow.setWindowTitle(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Asset Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Asset Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_anim_label.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Asset/Anim", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_type_episode_label.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_shot_label.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.task_label.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.open_pushButton.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.open_publish_pushButton.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Open Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.save_pushButton.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.wip_pushButton.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "WIP", None, QtGui.QApplication.UnicodeUTF8))
        self.publish_pushButton.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFiles.setTitle(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_project.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "New project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Asset.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "New Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Task.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "New Task", None, QtGui.QApplication.UnicodeUTF8))

