# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\development\Python\ml_pos_tool\PT.ui'
#
# Created: Sun Sep 25 14:12:36 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MPosToolMainWindow(object):
    def setupUi(self, MPosToolMainWindow):
        MPosToolMainWindow.setObjectName("MPosToolMainWindow")
        MPosToolMainWindow.resize(245, 290)
        MPosToolMainWindow.setMinimumSize(QtCore.QSize(245, 290))
        MPosToolMainWindow.setMaximumSize(QtCore.QSize(245, 290))
        MPosToolMainWindow.setBaseSize(QtCore.QSize(245, 290))
        self.centralwidget = QtGui.QWidget(MPosToolMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(115, 70))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ws_rB = QtGui.QRadioButton(self.groupBox_3)
        self.ws_rB.setChecked(True)
        self.ws_rB.setObjectName("ws_rB")
        self.verticalLayout_3.addWidget(self.ws_rB)
        self.os_rB = QtGui.QRadioButton(self.groupBox_3)
        self.os_rB.setObjectName("os_rB")
        self.verticalLayout_3.addWidget(self.os_rB)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(115, 0))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tx_cB = QtGui.QCheckBox(self.groupBox)
        self.tx_cB.setObjectName("tx_cB")
        self.verticalLayout.addWidget(self.tx_cB)
        self.ty_cB = QtGui.QCheckBox(self.groupBox)
        self.ty_cB.setObjectName("ty_cB")
        self.verticalLayout.addWidget(self.ty_cB)
        self.tz_cB = QtGui.QCheckBox(self.groupBox)
        self.tz_cB.setObjectName("tz_cB")
        self.verticalLayout.addWidget(self.tz_cB)
        self.rx_cB = QtGui.QCheckBox(self.groupBox)
        self.rx_cB.setObjectName("rx_cB")
        self.verticalLayout.addWidget(self.rx_cB)
        self.ry_cB = QtGui.QCheckBox(self.groupBox)
        self.ry_cB.setObjectName("ry_cB")
        self.verticalLayout.addWidget(self.ry_cB)
        self.rz_cB = QtGui.QCheckBox(self.groupBox)
        self.rz_cB.setObjectName("rz_cB")
        self.verticalLayout.addWidget(self.rz_cB)
        self.sx_cB = QtGui.QCheckBox(self.groupBox)
        self.sx_cB.setObjectName("sx_cB")
        self.verticalLayout.addWidget(self.sx_cB)
        self.sy_cB = QtGui.QCheckBox(self.groupBox)
        self.sy_cB.setObjectName("sy_cB")
        self.verticalLayout.addWidget(self.sy_cB)
        self.sz_cB = QtGui.QCheckBox(self.groupBox)
        self.sz_cB.setObjectName("sz_cB")
        self.verticalLayout.addWidget(self.sz_cB)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 2, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mirror_cB = QtGui.QCheckBox(self.groupBox_4)
        self.mirror_cB.setObjectName("mirror_cB")
        self.gridLayout_2.addWidget(self.mirror_cB, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.mirror_x_rB = QtGui.QRadioButton(self.groupBox_4)
        self.mirror_x_rB.setChecked(True)
        self.mirror_x_rB.setObjectName("mirror_x_rB")
        self.gridLayout_2.addWidget(self.mirror_x_rB, 2, 0, 1, 1)
        self.mirror_y_rB = QtGui.QRadioButton(self.groupBox_4)
        self.mirror_y_rB.setObjectName("mirror_y_rB")
        self.gridLayout_2.addWidget(self.mirror_y_rB, 3, 0, 1, 1)
        self.mirror_z_rB = QtGui.QRadioButton(self.groupBox_4)
        self.mirror_z_rB.setObjectName("mirror_z_rB")
        self.gridLayout_2.addWidget(self.mirror_z_rB, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.move_pB = QtGui.QPushButton(self.centralwidget)
        self.move_pB.setMinimumSize(QtCore.QSize(0, 30))
        self.move_pB.setObjectName("move_pB")
        self.gridLayout.addWidget(self.move_pB, 2, 0, 1, 2)
        self.move_even_pB = QtGui.QPushButton(self.centralwidget)
        self.move_even_pB.setMinimumSize(QtCore.QSize(0, 30))
        self.move_even_pB.setObjectName("move_even_pB")
        self.gridLayout.addWidget(self.move_even_pB, 3, 0, 1, 2)
        # MPosToolMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MPosToolMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MPosToolMainWindow)

    def retranslateUi(self, MPosToolMainWindow):
        MPosToolMainWindow.setWindowTitle(QtGui.QApplication.translate("MPosToolMainWindow", "Position Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.ws_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Perform transformation in world space", None, QtGui.QApplication.UnicodeUTF8))
        self.ws_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "World space", None, QtGui.QApplication.UnicodeUTF8))
        self.os_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Perform transformation in local space", None, QtGui.QApplication.UnicodeUTF8))
        self.os_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Object space", None, QtGui.QApplication.UnicodeUTF8))
        self.tx_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Translate X", None, QtGui.QApplication.UnicodeUTF8))
        self.ty_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Translate Y", None, QtGui.QApplication.UnicodeUTF8))
        self.tz_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Translate Z", None, QtGui.QApplication.UnicodeUTF8))
        self.rx_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Rotate X", None, QtGui.QApplication.UnicodeUTF8))
        self.ry_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Rotate Y", None, QtGui.QApplication.UnicodeUTF8))
        self.rz_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Rotate Z", None, QtGui.QApplication.UnicodeUTF8))
        self.sx_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Scale X", None, QtGui.QApplication.UnicodeUTF8))
        self.sy_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Scale Y", None, QtGui.QApplication.UnicodeUTF8))
        self.sz_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Scale Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_cB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Mirror the selected values", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Mirror ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_x_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Mirror axis : X", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_x_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_y_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Mirror axis : Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_y_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_z_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Mirror axis : Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_z_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.move_pB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "select one object : move based on its own coordinates. Select 2 objects : first one : source, second one : target ; move the second one on the base of the coordinates of the first one", None, QtGui.QApplication.UnicodeUTF8))
        self.move_pB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Move", None, QtGui.QApplication.UnicodeUTF8))
        self.move_even_pB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "multi selection : 1st object : first pair source, 2nd object : first pair target ; 3rd object : second pair source, 4th object : second pair target ; etc.", None, QtGui.QApplication.UnicodeUTF8))
        self.move_even_pB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Move by pair", None, QtGui.QApplication.UnicodeUTF8))

