# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\development\Python\mla_MayaPipe\mla_PosTool\PosTool.ui'
#
# Created: Mon Sep 25 22:43:02 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MPosToolMainWindow(object):
    def setupUi(self, MPosToolMainWindow):
        MPosToolMainWindow.setObjectName("MPosToolMainWindow")
        MPosToolMainWindow.resize(280, 400)
        MPosToolMainWindow.setMinimumSize(QtCore.QSize(280, 400))
        MPosToolMainWindow.setMaximumSize(QtCore.QSize(280, 400))
        MPosToolMainWindow.setBaseSize(QtCore.QSize(280, 375))
        self.centralwidget = QtGui.QWidget(MPosToolMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(115, 0))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.rx_cB = QtGui.QCheckBox(self.groupBox)
        self.rx_cB.setObjectName("rx_cB")
        self.gridLayout.addWidget(self.rx_cB, 5, 0, 1, 1)
        self.sx_cB = QtGui.QCheckBox(self.groupBox)
        self.sx_cB.setObjectName("sx_cB")
        self.gridLayout.addWidget(self.sx_cB, 9, 0, 1, 1)
        self.sy_cB = QtGui.QCheckBox(self.groupBox)
        self.sy_cB.setObjectName("sy_cB")
        self.gridLayout.addWidget(self.sy_cB, 10, 0, 1, 1)
        self.translate_cB = QtGui.QCheckBox(self.groupBox)
        self.translate_cB.setChecked(True)
        self.translate_cB.setObjectName("translate_cB")
        self.gridLayout.addWidget(self.translate_cB, 0, 0, 1, 1)
        self.ty_cB = QtGui.QCheckBox(self.groupBox)
        self.ty_cB.setChecked(True)
        self.ty_cB.setObjectName("ty_cB")
        self.gridLayout.addWidget(self.ty_cB, 2, 0, 1, 1)
        self.tx_cB = QtGui.QCheckBox(self.groupBox)
        self.tx_cB.setChecked(True)
        self.tx_cB.setObjectName("tx_cB")
        self.gridLayout.addWidget(self.tx_cB, 1, 0, 1, 1)
        self.rz_cB = QtGui.QCheckBox(self.groupBox)
        self.rz_cB.setObjectName("rz_cB")
        self.gridLayout.addWidget(self.rz_cB, 7, 0, 1, 1)
        self.rotate_cB = QtGui.QCheckBox(self.groupBox)
        self.rotate_cB.setObjectName("rotate_cB")
        self.gridLayout.addWidget(self.rotate_cB, 4, 0, 1, 1)
        self.tz_cB = QtGui.QCheckBox(self.groupBox)
        self.tz_cB.setChecked(True)
        self.tz_cB.setObjectName("tz_cB")
        self.gridLayout.addWidget(self.tz_cB, 3, 0, 1, 1)
        self.sz_cB = QtGui.QCheckBox(self.groupBox)
        self.sz_cB.setObjectName("sz_cB")
        self.gridLayout.addWidget(self.sz_cB, 11, 0, 1, 1)
        self.scale_cB = QtGui.QCheckBox(self.groupBox)
        self.scale_cB.setObjectName("scale_cB")
        self.gridLayout.addWidget(self.scale_cB, 8, 0, 1, 1)
        self.ry_cB = QtGui.QCheckBox(self.groupBox)
        self.ry_cB.setObjectName("ry_cB")
        self.gridLayout.addWidget(self.ry_cB, 6, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 1, 1, 1)

        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setMinimumSize(QtCore.QSize(115, 70))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ws_rB = QtGui.QRadioButton(self.groupBox_3)
        self.ws_rB.setChecked(True)
        self.ws_rB.setObjectName("ws_rB")
        self.verticalLayout_3.addWidget(self.ws_rB)
        self.os_rB = QtGui.QRadioButton(self.groupBox_3)
        self.os_rB.setObjectName("os_rB")
        self.verticalLayout_3.addWidget(self.os_rB)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.gridLayout_8.addWidget(self.groupBox_3, 0, 0, 1, 1)

        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mirror_cB = QtGui.QCheckBox(self.groupBox_4)
        self.mirror_cB.setObjectName("mirror_cB")
        self.gridLayout_2.addWidget(self.mirror_cB, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.mirror_x_rB = QtGui.QRadioButton(self.groupBox_4)
        self.mirror_x_rB.setChecked(True)
        self.mirror_x_rB.setObjectName("mirror_x_rB")
        self.gridLayout_2.addWidget(self.mirror_x_rB, 2, 0, 1, 1)
        self.mirror_y_rB = QtGui.QRadioButton(self.groupBox_4)
        self.mirror_y_rB.setObjectName("mirror_y_rB")
        self.gridLayout_2.addWidget(self.mirror_y_rB, 3, 0, 1, 1)
        self.mirror_z_rB = QtGui.QRadioButton(self.groupBox_4)
        self.mirror_z_rB.setObjectName("mirror_z_rB")
        self.gridLayout_2.addWidget(self.mirror_z_rB, 4, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setMinimumSize(QtCore.QSize(115, 70))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mirror_behavior_rB = QtGui.QRadioButton(self.groupBox_6)
        self.mirror_behavior_rB.setChecked(True)
        self.mirror_behavior_rB.setObjectName("mirror_behavior_rB")
        self.verticalLayout_5.addWidget(self.mirror_behavior_rB)
        self.mirror_scale_rB = QtGui.QRadioButton(self.groupBox_6)
        self.mirror_scale_rB.setChecked(False)
        self.mirror_scale_rB.setObjectName("mirror_scale_rB")
        self.verticalLayout_5.addWidget(self.mirror_scale_rB)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.move_pB = QtGui.QPushButton(self.tab)
        self.move_pB.setMinimumSize(QtCore.QSize(0, 30))
        self.move_pB.setObjectName("move_pB")
        self.gridLayout_8.addWidget(self.move_pB, 3, 0, 1, 1)
        self.move_even_pB = QtGui.QPushButton(self.tab)
        self.move_even_pB.setMinimumSize(QtCore.QSize(0, 30))
        self.move_even_pB.setObjectName("move_even_pB")
        self.gridLayout_8.addWidget(self.move_even_pB, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.maintain_offset_cB = QtGui.QCheckBox(self.tab_2)
        self.maintain_offset_cB.setChecked(True)
        self.maintain_offset_cB.setObjectName("maintain_offset_cB")
        self.gridLayout_7.addWidget(self.maintain_offset_cB, 0, 0, 1, 1)
        self.constrain_pB = QtGui.QPushButton(self.tab_2)
        self.constrain_pB.setMinimumSize(QtCore.QSize(0, 30))
        self.constrain_pB.setObjectName("constrain_pB")
        self.gridLayout_7.addWidget(self.constrain_pB, 4, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setEnabled(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.up_vectorX_sB = QtGui.QSpinBox(self.groupBox_5)
        self.up_vectorX_sB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.up_vectorX_sB.setMinimum(-1)
        self.up_vectorX_sB.setMaximum(1)
        self.up_vectorX_sB.setObjectName("up_vectorX_sB")
        self.gridLayout_6.addWidget(self.up_vectorX_sB, 0, 0, 1, 1)
        self.up_vectorY_sB = QtGui.QSpinBox(self.groupBox_5)
        self.up_vectorY_sB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.up_vectorY_sB.setMinimum(-1)
        self.up_vectorY_sB.setMaximum(1)
        self.up_vectorY_sB.setProperty("value", 1)
        self.up_vectorY_sB.setObjectName("up_vectorY_sB")
        self.gridLayout_6.addWidget(self.up_vectorY_sB, 0, 1, 1, 1)
        self.up_vectorZ_sB = QtGui.QSpinBox(self.groupBox_5)
        self.up_vectorZ_sB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.up_vectorZ_sB.setMinimum(-1)
        self.up_vectorZ_sB.setMaximum(1)
        self.up_vectorZ_sB.setObjectName("up_vectorZ_sB")
        self.gridLayout_6.addWidget(self.up_vectorZ_sB, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.aim_vectorX_sB = QtGui.QSpinBox(self.groupBox_2)
        self.aim_vectorX_sB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.aim_vectorX_sB.setMinimum(-1)
        self.aim_vectorX_sB.setMaximum(1)
        self.aim_vectorX_sB.setProperty("value", 1)
        self.aim_vectorX_sB.setObjectName("aim_vectorX_sB")
        self.gridLayout_5.addWidget(self.aim_vectorX_sB, 0, 0, 1, 1)
        self.aim_vectorY_sB = QtGui.QSpinBox(self.groupBox_2)
        self.aim_vectorY_sB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.aim_vectorY_sB.setMinimum(-1)
        self.aim_vectorY_sB.setMaximum(1)
        self.aim_vectorY_sB.setObjectName("aim_vectorY_sB")
        self.gridLayout_5.addWidget(self.aim_vectorY_sB, 0, 1, 1, 1)
        self.aim_vectorZ_sB = QtGui.QSpinBox(self.groupBox_2)
        self.aim_vectorZ_sB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.aim_vectorZ_sB.setMinimum(-1)
        self.aim_vectorZ_sB.setMaximum(1)
        self.aim_vectorZ_sB.setObjectName("aim_vectorZ_sB")
        self.gridLayout_5.addWidget(self.aim_vectorZ_sB, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.constrain_by_pair_pB = QtGui.QPushButton(self.tab_2)
        self.constrain_by_pair_pB.setMinimumSize(QtCore.QSize(0, 30))
        self.constrain_by_pair_pB.setObjectName("constrain_by_pair_pB")
        self.gridLayout_7.addWidget(self.constrain_by_pair_pB, 5, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.point_ct_rB = QtGui.QRadioButton(self.tab_2)
        self.point_ct_rB.setChecked(True)
        self.point_ct_rB.setObjectName("point_ct_rB")
        self.verticalLayout.addWidget(self.point_ct_rB)
        self.orient_ct_rB = QtGui.QRadioButton(self.tab_2)
        self.orient_ct_rB.setObjectName("orient_ct_rB")
        self.verticalLayout.addWidget(self.orient_ct_rB)
        self.aim_ct_rB = QtGui.QRadioButton(self.tab_2)
        self.aim_ct_rB.setObjectName("aim_ct_rB")
        self.verticalLayout.addWidget(self.aim_ct_rB)
        self.scale_ct_rB = QtGui.QRadioButton(self.tab_2)
        self.scale_ct_rB.setObjectName("scale_ct_rB")
        self.verticalLayout.addWidget(self.scale_ct_rB)
        self.parent_ct_rB = QtGui.QRadioButton(self.tab_2)
        self.parent_ct_rB.setObjectName("parent_ct_rB")
        self.verticalLayout.addWidget(self.parent_ct_rB)
        self.mirror_ct_rB = QtGui.QRadioButton(self.tab_2)
        self.mirror_ct_rB.setEnabled(True)
        self.mirror_ct_rB.setObjectName("mirror_ct_rB")
        self.verticalLayout.addWidget(self.mirror_ct_rB)
        self.gridLayout_7.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MPosToolMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MPosToolMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.aim_ct_rB, QtCore.SIGNAL("toggled(bool)"), self.groupBox_5.setEnabled)
        QtCore.QObject.connect(self.aim_ct_rB, QtCore.SIGNAL("toggled(bool)"), self.groupBox_2.setEnabled)
        QtCore.QObject.connect(self.translate_cB, QtCore.SIGNAL("toggled(bool)"), self.tx_cB.setChecked)
        QtCore.QObject.connect(self.translate_cB, QtCore.SIGNAL("toggled(bool)"), self.ty_cB.setChecked)
        QtCore.QObject.connect(self.translate_cB, QtCore.SIGNAL("toggled(bool)"), self.tz_cB.setChecked)
        QtCore.QObject.connect(self.point_ct_rB, QtCore.SIGNAL("toggled(bool)"), self.translate_cB.setChecked)
        QtCore.QObject.connect(self.parent_ct_rB, QtCore.SIGNAL("toggled(bool)"), self.translate_cB.setChecked)
        QtCore.QObject.connect(self.orient_ct_rB, QtCore.SIGNAL("toggled(bool)"), self.rotate_cB.setChecked)
        QtCore.QObject.connect(self.rotate_cB, QtCore.SIGNAL("toggled(bool)"), self.rx_cB.setChecked)
        QtCore.QObject.connect(self.rotate_cB, QtCore.SIGNAL("toggled(bool)"), self.rz_cB.setChecked)
        QtCore.QObject.connect(self.rotate_cB, QtCore.SIGNAL("toggled(bool)"), self.ry_cB.setChecked)
        QtCore.QObject.connect(self.scale_cB, QtCore.SIGNAL("toggled(bool)"), self.sx_cB.setChecked)
        QtCore.QObject.connect(self.scale_cB, QtCore.SIGNAL("toggled(bool)"), self.sy_cB.setChecked)
        QtCore.QObject.connect(self.scale_cB, QtCore.SIGNAL("toggled(bool)"), self.sz_cB.setChecked)
        QtCore.QObject.connect(self.scale_ct_rB, QtCore.SIGNAL("toggled(bool)"), self.scale_cB.setChecked)
        QtCore.QObject.connect(self.parent_ct_rB, QtCore.SIGNAL("toggled(bool)"), self.rotate_cB.setChecked)
        QtCore.QObject.connect(self.aim_ct_rB, QtCore.SIGNAL("toggled(bool)"), self.rotate_cB.setChecked)
        QtCore.QObject.connect(self.mirror_ct_rB, QtCore.SIGNAL("toggled(bool)"), self.constrain_by_pair_pB.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MPosToolMainWindow)
        MPosToolMainWindow.setTabOrder(self.tabWidget, self.ws_rB)
        MPosToolMainWindow.setTabOrder(self.ws_rB, self.os_rB)
        MPosToolMainWindow.setTabOrder(self.os_rB, self.mirror_cB)
        MPosToolMainWindow.setTabOrder(self.mirror_cB, self.mirror_x_rB)
        MPosToolMainWindow.setTabOrder(self.mirror_x_rB, self.mirror_y_rB)
        MPosToolMainWindow.setTabOrder(self.mirror_y_rB, self.mirror_z_rB)
        MPosToolMainWindow.setTabOrder(self.mirror_z_rB, self.move_pB)
        MPosToolMainWindow.setTabOrder(self.move_pB, self.move_even_pB)
        MPosToolMainWindow.setTabOrder(self.move_even_pB, self.translate_cB)
        MPosToolMainWindow.setTabOrder(self.translate_cB, self.tx_cB)
        MPosToolMainWindow.setTabOrder(self.tx_cB, self.ty_cB)
        MPosToolMainWindow.setTabOrder(self.ty_cB, self.tz_cB)
        MPosToolMainWindow.setTabOrder(self.tz_cB, self.rotate_cB)
        MPosToolMainWindow.setTabOrder(self.rotate_cB, self.rx_cB)
        MPosToolMainWindow.setTabOrder(self.rx_cB, self.ry_cB)
        MPosToolMainWindow.setTabOrder(self.ry_cB, self.rz_cB)
        MPosToolMainWindow.setTabOrder(self.rz_cB, self.scale_cB)
        MPosToolMainWindow.setTabOrder(self.scale_cB, self.sx_cB)
        MPosToolMainWindow.setTabOrder(self.sx_cB, self.sy_cB)
        MPosToolMainWindow.setTabOrder(self.sy_cB, self.sz_cB)
        MPosToolMainWindow.setTabOrder(self.sz_cB, self.maintain_offset_cB)
        MPosToolMainWindow.setTabOrder(self.maintain_offset_cB, self.aim_vectorX_sB)
        MPosToolMainWindow.setTabOrder(self.aim_vectorX_sB, self.aim_vectorY_sB)
        MPosToolMainWindow.setTabOrder(self.aim_vectorY_sB, self.aim_vectorZ_sB)
        MPosToolMainWindow.setTabOrder(self.aim_vectorZ_sB, self.up_vectorX_sB)
        MPosToolMainWindow.setTabOrder(self.up_vectorX_sB, self.up_vectorY_sB)
        MPosToolMainWindow.setTabOrder(self.up_vectorY_sB, self.up_vectorZ_sB)
        MPosToolMainWindow.setTabOrder(self.up_vectorZ_sB, self.point_ct_rB)
        MPosToolMainWindow.setTabOrder(self.point_ct_rB, self.orient_ct_rB)
        MPosToolMainWindow.setTabOrder(self.orient_ct_rB, self.aim_ct_rB)
        MPosToolMainWindow.setTabOrder(self.aim_ct_rB, self.scale_ct_rB)
        MPosToolMainWindow.setTabOrder(self.scale_ct_rB, self.parent_ct_rB)
        MPosToolMainWindow.setTabOrder(self.parent_ct_rB, self.mirror_ct_rB)
        MPosToolMainWindow.setTabOrder(self.mirror_ct_rB, self.constrain_pB)
        MPosToolMainWindow.setTabOrder(self.constrain_pB, self.constrain_by_pair_pB)

    def retranslateUi(self, MPosToolMainWindow):
        MPosToolMainWindow.setWindowTitle(QtGui.QApplication.translate("MPosToolMainWindow", "Position Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.rx_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "RX", None, QtGui.QApplication.UnicodeUTF8))
        self.sx_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "SX", None, QtGui.QApplication.UnicodeUTF8))
        self.sy_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "SY", None, QtGui.QApplication.UnicodeUTF8))
        self.translate_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Translate", None, QtGui.QApplication.UnicodeUTF8))
        self.ty_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "TY", None, QtGui.QApplication.UnicodeUTF8))
        self.tx_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "TX", None, QtGui.QApplication.UnicodeUTF8))
        self.rz_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "RZ", None, QtGui.QApplication.UnicodeUTF8))
        self.rotate_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Rotate", None, QtGui.QApplication.UnicodeUTF8))
        self.tz_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "TZ", None, QtGui.QApplication.UnicodeUTF8))
        self.sz_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "SZ", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.ry_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "RY", None, QtGui.QApplication.UnicodeUTF8))
        self.ws_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Perform transformation in world space", None, QtGui.QApplication.UnicodeUTF8))
        self.ws_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "World space", None, QtGui.QApplication.UnicodeUTF8))
        self.os_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Perform transformation in local space", None, QtGui.QApplication.UnicodeUTF8))
        self.os_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Object space", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_cB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Mirror the selected values", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Mirror ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_x_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Mirror axis : X", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_x_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_y_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Mirror axis : Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_y_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_z_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Mirror axis : Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_z_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_behavior_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Perform transformation in local space", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_behavior_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Behavior", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_scale_rB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "Perform transformation in world space", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_scale_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.move_pB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "select one object : move based on its own coordinates. Select 2 objects : first one : source, second one : target ; move the second one on the base of the coordinates of the first one", None, QtGui.QApplication.UnicodeUTF8))
        self.move_pB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Move", None, QtGui.QApplication.UnicodeUTF8))
        self.move_even_pB.setToolTip(QtGui.QApplication.translate("MPosToolMainWindow", "multi selection : 1st object : first pair source, 2nd object : first pair target ; 3rd object : second pair source, 4th object : second pair target ; etc.", None, QtGui.QApplication.UnicodeUTF8))
        self.move_even_pB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Move by pair", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MPosToolMainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.maintain_offset_cB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Maintain offset", None, QtGui.QApplication.UnicodeUTF8))
        self.constrain_pB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Constrain", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MPosToolMainWindow", "Up vector", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MPosToolMainWindow", "Aim vector", None, QtGui.QApplication.UnicodeUTF8))
        self.constrain_by_pair_pB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Constrain by pair", None, QtGui.QApplication.UnicodeUTF8))
        self.point_ct_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "pointConstraint", None, QtGui.QApplication.UnicodeUTF8))
        self.orient_ct_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "orientConstraint", None, QtGui.QApplication.UnicodeUTF8))
        self.aim_ct_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "aimConstraint", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_ct_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "scaleConstraint", None, QtGui.QApplication.UnicodeUTF8))
        self.parent_ct_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "parentConstraint", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_ct_rB.setText(QtGui.QApplication.translate("MPosToolMainWindow", "Mirror selected", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MPosToolMainWindow", "Constrain", None, QtGui.QApplication.UnicodeUTF8))

