# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\development\Python\ml_curve_manager\CM.ui'
#
# Created: Sun Sep 25 19:32:06 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CMMainWindow(object):
    def setupUi(self, CMMainWindow):
        CMMainWindow.setObjectName("CMMainWindow")
        CMMainWindow.resize(230, 300)
        CMMainWindow.setMinimumSize(QtCore.QSize(230, 300))
        CMMainWindow.setMaximumSize(QtCore.QSize(230, 300))
        self.centralwidget = QtGui.QWidget(CMMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(210, 270))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(54, 25))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.name_lE = QtGui.QLineEdit(self.tab)
        self.name_lE.setMinimumSize(QtCore.QSize(0, 25))
        self.name_lE.setMaximumSize(QtCore.QSize(128, 25))
        self.name_lE.setObjectName("name_lE")
        self.gridLayout.addWidget(self.name_lE, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setMaximumSize(QtCore.QSize(54, 25))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.curve_comB = QtGui.QComboBox(self.tab)
        self.curve_comB.setMinimumSize(QtCore.QSize(0, 25))
        self.curve_comB.setMaximumSize(QtCore.QSize(128, 25))
        self.curve_comB.setObjectName("curve_comB")
        self.gridLayout.addWidget(self.curve_comB, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setMaximumSize(QtCore.QSize(54, 25))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.orientation_rB_x = QtGui.QRadioButton(self.tab)
        self.orientation_rB_x.setObjectName("orientation_rB_x")
        self.horizontalLayout.addWidget(self.orientation_rB_x)
        self.orientation_rB_y = QtGui.QRadioButton(self.tab)
        self.orientation_rB_y.setObjectName("orientation_rB_y")
        self.horizontalLayout.addWidget(self.orientation_rB_y)
        self.orientation_rB_z = QtGui.QRadioButton(self.tab)
        self.orientation_rB_z.setObjectName("orientation_rB_z")
        self.horizontalLayout.addWidget(self.orientation_rB_z)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setMaximumSize(QtCore.QSize(54, 25))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mirror_cB_x = QtGui.QCheckBox(self.tab)
        self.mirror_cB_x.setObjectName("mirror_cB_x")
        self.horizontalLayout_2.addWidget(self.mirror_cB_x)
        self.mirror_cB_y = QtGui.QCheckBox(self.tab)
        self.mirror_cB_y.setObjectName("mirror_cB_y")
        self.horizontalLayout_2.addWidget(self.mirror_cB_y)
        self.mirror_cB_z = QtGui.QCheckBox(self.tab)
        self.mirror_cB_z.setObjectName("mirror_cB_z")
        self.horizontalLayout_2.addWidget(self.mirror_cB_z)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.creation_pB = QtGui.QPushButton(self.tab)
        self.creation_pB.setMinimumSize(QtCore.QSize(0, 25))
        self.creation_pB.setMaximumSize(QtCore.QSize(188, 25))
        self.creation_pB.setObjectName("creation_pB")
        self.gridLayout.addWidget(self.creation_pB, 4, 0, 1, 2)
        self.remove_shape_cB = QtGui.QCheckBox(self.tab)
        self.remove_shape_cB.setMinimumSize(QtCore.QSize(0, 25))
        self.remove_shape_cB.setObjectName("remove_shape_cB")
        self.gridLayout.addWidget(self.remove_shape_cB, 5, 0, 1, 2)
        self.curve_edition_pB = QtGui.QPushButton(self.tab)
        self.curve_edition_pB.setMinimumSize(QtCore.QSize(0, 25))
        self.curve_edition_pB.setMaximumSize(QtCore.QSize(188, 25))
        self.curve_edition_pB.setObjectName("curve_edition_pB")
        self.gridLayout.addWidget(self.curve_edition_pB, 6, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.new_shape_lE = QtGui.QLineEdit(self.tab_2)
        self.new_shape_lE.setMinimumSize(QtCore.QSize(0, 25))
        self.new_shape_lE.setObjectName("new_shape_lE")
        self.gridLayout_2.addWidget(self.new_shape_lE, 0, 1, 1, 1)
        self.save_to_dict_pB = QtGui.QPushButton(self.tab_2)
        self.save_to_dict_pB.setMinimumSize(QtCore.QSize(0, 25))
        self.save_to_dict_pB.setObjectName("save_to_dict_pB")
        self.gridLayout_2.addWidget(self.save_to_dict_pB, 1, 0, 1, 2)
        self.delete_shape_pB = QtGui.QPushButton(self.tab_2)
        self.delete_shape_pB.setMinimumSize(QtCore.QSize(0, 25))
        self.delete_shape_pB.setObjectName("delete_shape_pB")
        self.gridLayout_2.addWidget(self.delete_shape_pB, 3, 0, 1, 2)
        self.curve_to_delete_comB = QtGui.QComboBox(self.tab_2)
        self.curve_to_delete_comB.setMinimumSize(QtCore.QSize(0, 25))
        self.curve_to_delete_comB.setMaximumSize(QtCore.QSize(123, 25))
        self.curve_to_delete_comB.setObjectName("curve_to_delete_comB")
        self.gridLayout_2.addWidget(self.curve_to_delete_comB, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setMaximumSize(QtCore.QSize(59, 25))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        # CMMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CMMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CMMainWindow)

    def retranslateUi(self, CMMainWindow):
        CMMainWindow.setWindowTitle(QtGui.QApplication.translate("CMMainWindow", "Curve Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CMMainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CMMainWindow", "Curve", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CMMainWindow", "Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.orientation_rB_x.setText(QtGui.QApplication.translate("CMMainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.orientation_rB_y.setText(QtGui.QApplication.translate("CMMainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.orientation_rB_z.setText(QtGui.QApplication.translate("CMMainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CMMainWindow", "Mirror", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_cB_x.setText(QtGui.QApplication.translate("CMMainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_cB_y.setText(QtGui.QApplication.translate("CMMainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mirror_cB_z.setText(QtGui.QApplication.translate("CMMainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.creation_pB.setText(QtGui.QApplication.translate("CMMainWindow", "Creation", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_shape_cB.setText(QtGui.QApplication.translate("CMMainWindow", "Remove Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.curve_edition_pB.setText(QtGui.QApplication.translate("CMMainWindow", "Edition", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("CMMainWindow", "Creation/Edition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CMMainWindow", "Shape name", None, QtGui.QApplication.UnicodeUTF8))
        self.save_to_dict_pB.setText(QtGui.QApplication.translate("CMMainWindow", "Save / Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_shape_pB.setText(QtGui.QApplication.translate("CMMainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CMMainWindow", "Curve name", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("CMMainWindow", "Managing", None, QtGui.QApplication.UnicodeUTF8))

